import Head from "next/head";
import { Poppins } from "next/font/google";
import Characters from "@src/components/Characters/Characters";
import Loading from "@src/components/Loading/Loading";
import Background from "@src/components/Background/Background";
import Link from "next/link";
import Image from "next/image";
import PageScroll from "@src/components/PageScroll/PageScroll";
import ShakyKanjiBlock from "@src/components/ShakyKanjiBlock/ShakyKanjiBlock";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

function SocialIcon({ href, src, alt }) {
  return (
    <Link href={href} target="_blank" rel="noopener noreferrer">
      <Image
        src={src}
        alt={alt}
        width={40}
        height={40}
        className="w-10 h-10 transition-transform duration-300 cursor-pointer hover:scale-90"
      />
    </Link>
  );
}

export default function Home() {
  const socialLinks = [
    {
      href: "https://discord.com/invite/PmWf27cY6p",
      src: "/assets/discord.svg",
      alt: "Discord",
    },
    {
      href: "https://opensea.io/ja/collection/fluffy-hugs89",
      src: "/assets/opensea.svg",
      alt: "OpenSea",
    },
    {
      href: "https://x.com/FluffyHUGS_prj",
      src: "/assets/twitter.svg",
      alt: "Twitter",
    },
  ];

  return (
    <div className={poppins.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageScroll>
          <section className="h-screen bg-secondary w-[100vw]">
            <div className="w-[25rem] h-6 relative z-10 py-6 mx-6">
              <Image
                src="/assets/logo.webp"
                alt="logo"
                width={400}
                height={400}
              />
            </div>
            <Background></Background>
            <Characters></Characters>
          </section>

          <section className="w-full h-screen bg-secondary">
            <div className="container mx-auto flex items-center justify-center h-full max-w-[800px] px-4 relative z-10">
              <img src="/assets/logo.webp" alt="logo" />
            </div>
          </section>
          <section className="flex items-center justify-end w-full h-screen bg-secondary">
            <div className="w-full max-w-3xl px-8"> {/* Added container with max-width */}
              <ShakyKanjiBlock
                lines={[
                  "ふわふわの動物たちに、",
                  "囲まれて暮らしたい",
                  "ペットや動物が大好きなあなたへ",
                ]}
              />
            </div>
          </section>
        </PageScroll>
        <div className="fixed bottom-0 z-20 flex items-center justify-between w-full mx-6 mb-10">
          <div className="flex items-center space-x-4">
            {socialLinks.map((link, index) => (
              <SocialIcon
                key={index}
                href={link.href}
                src={link.src}
                alt={link.alt}
              />
            ))}
          </div>
          <div className="relative h-6 px-4 w-fit">
            <Link
              href="https://nft.fluffyhugs.io/gallery"
              target="_blank"
              rel="noopener noreferrer"
              className="absolute mx-auto text-white left-12 md:left-20"
            >
              View collection
            </Link>
            <Image
              src="/assets/view.svg"
              alt="view-collection"
              width={250}
              height={250}
              className="-mt-28 md:-mt-32 w-[200px] h-[200px] md:w-[250px] md:h-[250px] transition-transform duration-300"
            />
          </div>
        </div>
        <Loading></Loading>
      </main>
    </div>
  );
}
